import { CCOrg, Organization } from "typings/sharedTypes"

export const sampleCoComOrgs = (): CCOrg[] => {
    return [
      { ccmd: 'AFRICOM', organizations: ['AFDW', 'JFHQ-ID'] },
      { ccmd: 'CENTCOM', organizations: ['WCG'] },
      {
        ccmd: 'EUCOM',
        organizations: [
          'DOIM',
          'NMCS',
          'NMCSO  SD',
          'NMCSO LANT',
          'NMCSO NORTHWEST',
          'NMCSO PAC',
          'NMCSO PUGET SOUND',
          'VA',
          'VAQWINGPAC',
          'NMCSO SAN DIEGO',
          'NMCSO SOUTHWEST',
          'NMCSOPAC',
          'NMCSOSANDIEGO',
          'NMSC',
          'NMSCO NORTHWEST',
          'NMSCO SAN DIEGO',
          'NMSCO SOUTHWEST',
          'NMSCOSD',
        ],
      },
      {
        ccmd: 'INDOPACOM',
        organizations: [
          'MARFORCOM',
          'MARFORPAC',
          'MAGTFTC',
          'MCAGCC29PALMS',
          'MCBCPPENDLETON',
          'MCBH',
          'MCIMIDPAC',
          'PACAF',
          '11AF',
          '141ACS',
          '142CF',
          '143CF',
          '144CF',
          '145AW',
          '145CF',
          '13AF',
          '20AF',
          '7AF',
          '137ARW',
          '137CF',
          '138CF',
          '139CF',
          'AAC',
          'AC',
          'ACC',
        ],
      },
      { ccmd: 'NORTHCOM', organizations: ['JFMONORTH', 'FMFLANT', 'AIRLANT'] },
    ]
  }
  
  /*
  Queries for the list of organizations. Returns an
  array of JSON objects in the following format:
      {
          "id": "unique identifier, e.g. org1",
          "organization": "used to group the organizations on the UI",
          "value": "the name of the organization, e.g. Brigade",
          "label": "the name of the organization, e.g. Brigade"
      }
  */
  export const sampleOrganizations = (): Organization[] => {
    return [
      { id: '11AF', organization: 'Air Force', value: '11AF', label: '11AF' },
      { id: '137ARW', organization: 'Air Force', value: '137ARW', label: '137ARW' },
      { id: '137CF', organization: 'Air Force', value: '137CF', label: '137CF' },
      { id: '138CF', organization: 'Air Force', value: '138CF', label: '138CF' },
      { id: '139CF', organization: 'Air Force', value: '139CF', label: '139CF' },
      { id: '13AF', organization: 'Air Force', value: '13AF', label: '13AF' },
      { id: '141ACS', organization: 'Air Force', value: '141ACS', label: '141ACS' },
      { id: '142CF', organization: 'Air Force', value: '142CF', label: '142CF' },
      { id: '143CF', organization: 'Air Force', value: '143CF', label: '143CF' },
      { id: '144CF', organization: 'Air Force', value: '144CF', label: '144CF' },
      { id: '145AW', organization: 'Air Force', value: '145AW', label: '145AW' },
      { id: '145CF', organization: 'Air Force', value: '145CF', label: '145CF' },
      { id: '1SOSOW', organization: 'Air Force', value: '1SOSOW', label: '1SOSOW' },
      { id: '1SOW', organization: 'Air Force', value: '1SOW', label: '1SOW' },
      { id: '20AF', organization: 'Air Force', value: '20AF', label: '20AF' },
      { id: '27SOW', organization: 'Air Force', value: '27SOW', label: '27SOW' },
      { id: '720STG', organization: 'Air Force', value: '720STG', label: '720STG' },
      { id: '7AF', organization: 'Air Force', value: '7AF', label: '7AF' },
      { id: 'AAC', organization: 'Air Force', value: 'AAC', label: 'AAC' },
      { id: 'AC', organization: 'Air Force', value: 'AC', label: 'AC' },
      { id: 'ACC', organization: 'Air Force', value: 'ACC', label: 'ACC' },
      { id: 'AFDW', organization: 'Air Force', value: 'AFDW', label: 'AFDW' },
      { id: 'AFSOC', organization: 'Air Force', value: 'AFSOC', label: 'AFSOC' },
      { id: 'AIRLANT', organization: 'Air Force', value: 'AIRLANT', label: 'AIRLANT' },
      { id: 'BHT', organization: 'Army', value: 'BHT', label: 'BHT' },
      { id: 'CMCBPAC', organization: 'Marine', value: 'CMCBPAC', label: 'CMCBPAC' },
      { id: 'DIRPUBSAFETY', organization: 'Army', value: 'DIRPUBSAFETY', label: 'DIRPUBSAFETY' },
      { id: 'DOIM', organization: 'Marine', value: 'DOIM', label: 'DOIM' },
      { id: 'FMFLANT', organization: 'Air Force', value: 'FMFLANT', label: 'FMFLANT' },
      { id: 'JFHQ-ID', organization: 'Air Force', value: 'JFHQ-ID', label: 'JFHQ-ID' },
      { id: 'JFMONORTH', organization: 'Air Force', value: 'JFMONORTH', label: 'JFMONORTH' },
      { id: 'MAGTFTC', organization: 'Marine', value: 'MAGTFTC', label: 'MAGTFTC' },
      { id: 'MARFORCOM', organization: 'Marine', value: 'MARFORCOM', label: 'MARFORCOM' },
      { id: 'MARFORPAC', organization: 'Marine', value: 'MARFORPAC', label: 'MARFORPAC' },
      { id: 'MCAGCC29PALMS', organization: 'Marine', value: 'MCAGCC29PALMS', label: 'MCAGCC29PALMS' },
      { id: 'MCBCPPENDLETON', organization: 'Marine', value: 'MCBCPPENDLETON', label: 'MCBCPPENDLETON' },
      { id: 'MCBH', organization: 'Marine', value: 'MCBH', label: 'MCBH' },
      { id: 'MCIMIDPAC', organization: 'Marine', value: 'MCIMIDPAC', label: 'MCIMIDPAC' },
      { id: 'MDA', organization: 'Army', value: 'MDA', label: 'MDA' },
      { id: 'MICOM', organization: 'Army', value: 'MICOM', label: 'MICOM' },
      { id: 'NMCS', organization: 'Marine', value: 'NMCS', label: 'NMCS' },
      { id: 'NMCSO  SD', organization: 'Marine', value: 'NMCSO  SD', label: 'NMCSO  SD' },
      { id: 'NMCSO LANT', organization: 'Marine', value: 'NMCSO LANT', label: 'NMCSO LANT' },
      { id: 'NMCSO NORTHWEST', organization: 'Navy', value: 'NMCSO NORTHWEST', label: 'NMCSO NORTHWEST' },
      { id: 'NMCSO PAC', organization: 'Marine', value: 'NMCSO PAC', label: 'NMCSO PAC' },
      { id: 'NMCSO PUGET SOUND', organization: 'Navy', value: 'NMCSO PUGET SOUND', label: 'NMCSO PUGET SOUND' },
      { id: 'NMCSO SAN DIEGO', organization: 'Marine', value: 'NMCSO SAN DIEGO', label: 'NMCSO SAN DIEGO' },
      { id: 'NMCSO SOUTHWEST', organization: 'Navy', value: 'NMCSO SOUTHWEST', label: 'NMCSO SOUTHWEST' },
      { id: 'NMCSOPAC', organization: 'Marine', value: 'NMCSOPAC', label: 'NMCSOPAC' },
      { id: 'NMCSOSANDIEGO', organization: 'Marine', value: 'NMCSOSANDIEGO', label: 'NMCSOSANDIEGO' },
      { id: 'NMSC', organization: 'Marine', value: 'NMSC', label: 'NMSC' },
      { id: 'NMSCO NORTHWEST', organization: 'Navy', value: 'NMSCO NORTHWEST', label: 'NMSCO NORTHWEST' },
      { id: 'NMSCO SAN DIEGO', organization: 'Navy', value: 'NMSCO SAN DIEGO', label: 'NMSCO SAN DIEGO' },
      { id: 'NMSCO SOUTHWEST', organization: 'Marine', value: 'NMSCO SOUTHWEST', label: 'NMSCO SOUTHWEST' },
      { id: 'NMSCOSD', organization: 'Navy', value: 'NMSCOSD', label: 'NMSCOSD' },
      { id: 'PACAF', organization: 'Air Force', value: 'PACAF', label: 'PACAF' },
      { id: 'VA', organization: 'Navy', value: 'VA', label: 'VA' },
      { id: 'VAQWINGPAC', organization: 'Navy', value: 'VAQWINGPAC', label: 'VAQWINGPAC' },
      { id: 'JSC', organization: 'Joint/Other', value: 'JSC', label: 'JSC' },
      { id: 'DISA', organization: 'Joint/Other', value: 'DISA', label: 'DISA' },
      { id: 'JEMSIAF', organization: 'Joint/Other', value: 'JEMSIAF', label: 'JEMSIAF' },
      { id: 'DARPA', organization: 'Joint/Other', value: 'DARPA', label: 'DARPA' },
    ]
  }
  